# Generated by Django 5.2.1 on 2025-09-18 06:03

import django.db.models.deletion
import django.utils.timezone
import photobooth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoboothSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Event name (e.g., 'John & Jane Wedding')", max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_base_url', models.URLField(blank=True, help_text='Base URL for QR codes (e.g., your domain)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoboothSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_resolution_width', models.IntegerField(default=1920)),
                ('camera_resolution_height', models.IntegerField(default=1080)),
                ('camera_fps', models.IntegerField(default=30)),
                ('photo_quality', models.IntegerField(default=95, help_text='JPEG quality (1-100)')),
                ('enable_filters', models.BooleanField(default=True)),
                ('countdown_seconds', models.IntegerField(default=3)),
                ('welcome_message', models.TextField(default='Welcome to our Wedding Photobooth!')),
                ('instructions', models.TextField(default='Position yourselves in front of the camera and smile!')),
                ('show_gallery_preview', models.BooleanField(default=True)),
                ('max_photos_per_session', models.IntegerField(default=1000)),
                ('auto_cleanup_days', models.IntegerField(default=30, help_text='Delete photos older than X days')),
            ],
            options={
                'verbose_name': 'Photobooth Settings',
                'verbose_name_plural': 'Photobooth Settings',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=photobooth.models.photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=photobooth.models.photo_upload_path)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('guest_name', models.CharField(blank=True, help_text='Optional guest name', max_length=200)),
                ('guest_email', models.EmailField(blank=True, help_text='Optional email for photo delivery', max_length=254)),
                ('is_processed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photobooth.photoboothsession')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
