# Generated by Django 5.2.1 on 2025-09-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photoboothsession',
            name='code',
            field=models.CharField(default='ABC123', help_text='Easy random code for joining the event', max_length=8),
        ),
        migrations.AddField(
            model_name='photoboothsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photoboothsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this event is currently active'),
        ),
    ]
