# Generated by Django 5.2.1 on 2025-09-18 07:17

import photobooth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_photoboothsession_code_photoboothsession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothsession',
            name='code',
            field=models.CharField(default=photobooth.models.generate_event_code, help_text='Easy random code for joining the event', max_length=8, unique=True),
        ),
    ]
