# Generated by Django 5.2.1 on 2025-09-18 07:27

import django.db.models.deletion
import django.utils.timezone
import photobooth.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0004_rename_photoboothsession_to_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Event name (e.g., 'John & Jane Wedding')", max_length=200)),
                ('code', models.CharField(default=photobooth.models.generate_event_code, help_text='Easy random code for joining the event', max_length=8, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_base_url', models.URLField(blank=True, help_text='Base URL for QR codes (e.g., your domain)')),
                ('created_by', models.ForeignKey(help_text='User who created the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photobooth.event'),
        ),
        migrations.DeleteModel(
            name='PhotoboothSession',
        ),
    ]
